#include <Arduino.h>
#include "wave_generator.h"
#include "pins.h"

#define PWM_RESOLUTION 8 // Resolução de 8 bits (0-255)
//const int pwmResolution = 8; // Resolução de 8 bits (0-255)
const int DUTY_50 = 50; // Resolução de 8 bits (0-255)

void setup() {
  // Configuração do PWM
  setupPWM(PIN_RPM, CHANNEL_RPM, PWM_RESOLUTION);
  setupPWM(PIN_INJECTOR_A, CHANNEL_INJECTOR_A, PWM_RESOLUTION);
  setupPWM(PIN_INJECTOR_B, CHANNEL_INJECTOR_B, PWM_RESOLUTION);
  setupPWM(PIN_INJECTOR_C, CHANNEL_INJECTOR_C, PWM_RESOLUTION);
  setupPWM(PIN_INJECTOR_D, CHANNEL_INJECTOR_D, PWM_RESOLUTION);
  setupPWM(PIN_MANOMETER, CHANNEL_MANOMETER, PWM_RESOLUTION);
  setupPWM(PIN_MAP_REDUCTOR, CHANNEL_MAP_REDUCTOR, PWM_RESOLUTION);
  setupPWM(PIN_MAP_COLECTOR, CHANNEL_MAP_COLECTOR, PWM_RESOLUTION);
  setupPWM(PIN_TEMP_GNV, CHANNEL_TEMP_GNV, PWM_RESOLUTION);
  setupPWM(PIN_HPS, CHANNEL_HPS, PWM_RESOLUTION);
  setupPWM(PIN_LPS, CHANNEL_LPS, PWM_RESOLUTION);

  // Setando como saida
  pinMode(PIN_RPM, OUTPUT);
  pinMode(PIN_INJECTOR_A, OUTPUT);
  pinMode(PIN_INJECTOR_B, OUTPUT);
  pinMode(PIN_INJECTOR_C, OUTPUT);
  pinMode(PIN_INJECTOR_D, OUTPUT);
  pinMode(PIN_MANOMETER, OUTPUT);
  pinMode(PIN_MAP_REDUCTOR, OUTPUT);
  pinMode(PIN_MAP_COLECTOR, OUTPUT);
  pinMode(PIN_TEMP_GNV, OUTPUT);
  pinMode(PIN_HPS, OUTPUT);
  pinMode(PIN_LPS, OUTPUT);
}

void loop() {
    setPWM(CHANNEL_RPM, 5000, DUTY_50);
    setPWM(CHANNEL_INJECTOR_A, 5000, DUTY_50);
    setPWM(CHANNEL_INJECTOR_B, 5000, DUTY_50);
    setPWM(CHANNEL_INJECTOR_C, 5000, DUTY_50);
    setPWM(CHANNEL_INJECTOR_D, 5000, DUTY_50);
    setPWM(CHANNEL_MANOMETER, 5000, DUTY_50);
    setPWM(CHANNEL_MAP_REDUCTOR, 5000, DUTY_50);
    setPWM(CHANNEL_MAP_COLECTOR, 5000, DUTY_50);
    setPWM(CHANNEL_TEMP_GNV, 5000, DUTY_50);
    setPWM(CHANNEL_HPS, 5000, DUTY_50);
    setPWM(CHANNEL_LPS, 5000, DUTY_50);
    delay(500);
}